Add Labels.numpy and organize fixtures
talmolab/sleap-io pull request #13
Opened 2022-08-25 23:15 UTC by roomrys

### Description
Add a `Labels.numpy` method that converts a `Labels` object to a numpy. Also reorganize the fixtures and add the video for the centered_pair_predictions.slp.

### Types of changes

- [ ] Bugfix
- [x] New feature
- [ ] Refactor / Code style update (no logical changes)
- [ ] Build / CI changes
- [ ] Documentation Update
- [ ] Other (explain)

### Does this address any currently open issues?
[list open issues here]

### Outside contributors checklist

- [ ] Review the [guidelines for contributing](https://github.com/talmolab/sleap-io/blob/main/CONTRIBUTING.md) to this repository
- [ ] Add tests that prove your fix is effective or that your feature works
- [ ] Add necessary documentation (if appropriate)

#### Thank you for contributing to SLEAP-IO!
:heart:

2022-08-26 19:05 UTC, roomrys commented on sleap_io/model/labeled_frame.py
>          return pts
Modified s.t. `labeled_frame.numpy` returns points only even if there are `PredictedInstances`. The other option is to make `labeled_frame.numpy` always return 3 coordinates with the last coordinate (the score) equal to `np.nan` if type is `Instance`. The current solution (no score returned) seems cleaner and more consistent to me personally.

2022-09-02 23:51 UTC, talmo requested changes
Minor fix

2022-09-02 23:51 UTC, talmo commented on sleap_io/model/labels.py
> +        print(f"video = {video}")
Remove this print statement

2022-09-06 17:57 UTC, talmo approved these changes
lgtm

2022-09-06 18:31 UTC, merged