MV (1): Add CameraGroup class
talmolab/sleap-io pull request #146
Opened 2024-11-27 17:42 UTC by roomrys

2024-11-27 20:15 UTC, talmo approved these changes
LGTM! Very clean :)

2025-01-21 16:43 UTC, talmo requested changes
Some suggestions, mostly minor

2025-01-21 16:43 UTC, talmo commented on sleap_io/model/camera.py
> +        return points_3d.reshape(*points_shape[1:-1], 3)
Added some logic for preserving dtype.

```suggestion
        # Undistort points
        points_dtype = points.dtype
        points = points.astype("float64")  # Ensure float64 for opencv undistort
        for cam_idx, camera in enumerate(self.cameras):
            cam_points = camera.undistort_points(points[cam_idx])
            points[cam_idx] = cam_points

        # Since points are undistorted, use extrinsic matrices as projection matrices
        projection_matrices = np.array(
            [camera.extrinsic_matrix[:3] for camera in self.cameras]
        )

        # Triangulate points using provided function
        points_3d = triangulation_func(points, projection_matrices)
        n_points_returned = points_3d.shape[0]
        if n_points_returned != n_points:
            raise ValueError(
                f"Expected triangulation function to return {n_points} 3D points, but "
                f"received {n_points_returned} 3D points."
            )

        # Reshape to (N, 3) and cast to the original dtype.
        points_3d = points_3d.reshape(*points_shape[1:-1], 3).astype(points_dtype)
        return points_3d
```

2025-01-21 16:43 UTC, talmo commented on sleap_io/model/camera.py
> +    points_3d = np.array(points_3d)
```suggestion
    # Remove rows with NaNs before SVD which may result in a ragged A (hence for loop)
    points_3d = []
    for a_slice in a:
        # Check that we have at least 2 views worth of non-nan points.
        nan_mask = np.isnan(a_slice)  # 2M x 4
        has_enough_matches = np.all(~nan_mask, axis=1).sum(axis=1) >= 4
        
        point_3d = np.full(3, np.nan)
        if has_enough_matches:
            a_no_nan = a_slice[~nan_mask].reshape(-1, 4, order="C")
            _, _, vh = np.linalg.svd(a_no_nan)
            point_3d = vh[-1, :-1] / vh[-1, -1]
            
        points_3d.append(point_3d)

    points_3d = np.array(points_3d)
```

2025-01-21 16:43 UTC, talmo commented on sleap_io/model/camera.py
> +        return projected_points.reshape(n_cameras, *points_shape[:-1], 2)
```suggestion
        points = points.astype(np.float64)
        points_shape = points.shape
        points_dtype = points.dtype
        try:
            # Check if points are 3D
            if points_shape[-1] != 3:
                raise ValueError
        except Exception as e:
            raise ValueError(
                "Expected points to be an array of 3D points of shape (..., 3) "
                "where '...' is any number of non-zero dimensions, but received shape "
                f"{points_shape}.\n\n{e}"
            )

        # Project 3D points to 2D for each camera
        n_cameras = len(self.cameras)
        n_points = np.prod(points_shape[:-1])
        projected_points = np.zeros((n_cameras, n_points, 2))
        for cam_idx, camera in enumerate(self.cameras):
            cam_points = camera.project(points)
            projected_points[cam_idx] = cam_points.reshape(n_points, 2)

        return projected_points.reshape(n_cameras, *points_shape[:-1], 2).astype(points_dtype)
```

2025-01-21 17:15 UTC, talmo commented
Regarding CI failing: see this commit --> https://github.com/talmolab/sleap-io/pull/143/commits/1637f707aa9453d6437757a661a8001a5106a219

2025-01-21 22:36 UTC, roomrys commented
I totally deranged the git history when I rebased... but, after fixing the merge conflicts, the diff is correct.

2025-01-22 00:31 UTC, talmo approved these changes

2025-01-22 01:16 UTC, merged