Change equality semantics for Points and Instances
talmolab/sleap-io pull request #21
Opened 2022-09-29 15:46 UTC by quantumdot

### Description
Changes to data model to enable sensible equality semantics for `Point`s and `Instance`s.

- Fix equality of `Points`. `X` and `Y` coordinates were previously compared using normal float equality semantics. Here we change to utilize the `numpy.isclose()` method for comparison, where two floats are compared for equality within some tolerance (we use just the default tolerances). Additionally, we will consider that two `NaN` values are equal, which is normally not true.
- Allow `Instance` objects to be compared for equality. The `Instance.points` collections compared with the rule that both collections of points must contain the same set of nodes, and for each node the point must be equal according to the semantics described above for `Point`s.

### Types of changes

- [ ] Bugfix
- [x] New feature
- [ ] Refactor / Code style update (no logical changes)
- [ ] Build / CI changes
- [ ] Documentation Update
- [ ] Other (explain)

### Does this address any currently open issues?
[list open issues here]

### Outside contributors checklist

- [x] Review the [guidelines for contributing](https://github.com/talmolab/sleap-io/blob/main/CONTRIBUTING.md) to this repository
- [x] Add tests that prove your fix is effective or that your feature works
- [x] Add necessary documentation (if appropriate)

#### Thank you for contributing to SLEAP-IO!
:heart:

2022-09-29 15:48 UTC, quantumdot commented
@talmo Let's start with this PR, as tests written for the other PR's would rely on the proposed changes here.

2022-09-30 18:25 UTC, talmo reviewed
The implementation looks good to me!

I appreciate the need for accounting for NaNs when doing equality comparison, but just so I have some clarity on the motivation: why are we allowing for float precision errors? In what cases does this come up?

My only concern is that leaving in some arbitrary wiggle room may lead to divergent results in the future, especially when doing equality comparisons for algorithmic correctness.

2022-09-30 22:15 UTC, quantumdot commented
One motivation came from testing the label-studio implementation, particularly when testing that a round trip from `Labels -> json -> Labels` produces the same data. Label studio uses relative point coordinates in the range of `[0-100]`. When converting from `Labels` to label-studio json, we divide `x` and `y` by `width` and `height` (respectively) and multiply by 100. Conversion from label-studio json to `Labels` does the inverse calculation. This can introduce minor floating point errors, so the fuzzy comparison helps when confirming a round trip for the data works.

The tolerance allowed in the comparison is on the order of 10^-2, which I think is below the precision of human annotators and DL models. The floating point error I noticed was on the order of 10^-13. [`np.isclose()`](https://numpy.org/doc/stable/reference/generated/numpy.isclose.html) allows setting absolute and relative tolerances via the `atol` and `rtol` parameters, and uses the following equation to compute equivalence:
```
absolute(a - b) <= (atol + rtol * absolute(b))
```
For an image 1024px in width, two `x`'s would be allowed to differ by `(10^-8 + 1024 * 10^-5) = 0.01024001px`. We can tune, or make available for the user to set, the specific tolerance level(s) they will accept.

2022-10-03 22:58 UTC, roomrys requested changes
Lets make it optional to allow precision error for the `__eq__` `Point` comparison. I have an implementation suggested here - let me know what you think. 

I think the option to allow precision error should be a standalone choice when making the comparison, i.e. `p1 == [p2, True]`. However, this requires an extra argument to be passed during point comparison, hence the list.

2022-10-03 22:58 UTC, roomrys commented on sleap_io/model/instance.py
> +    return bool(np.all(np.isclose(a, b, equal_nan=True)))
```suggestions

```

2022-10-03 22:58 UTC, roomrys commented on sleap_io/model/instance.py
> +    y: float = field(eq=cmp_using(eq=_safe_float_comparison))  # type: ignore
```suggestions
x: float
y: float
```

2022-10-03 22:58 UTC, roomrys commented on sleap_io/model/instance.py
```suggestion

    def __eq__(self, other: Point, allow_precision_error=False):
        """Compare `self` and `other` for equality, optionally allowing precision error.

        Args:
            self, other: instances of `Point` to compare

        Returns:
            True if all attributes of `self` and `other` are the identical (allowing
            precision error for `x` and `y` attributes if `allow_precision_error` is 
            True).
        """
        if isinstance(other, list):
            allow_precision_error = other[1]
            other = other[0]

        if allow_precision_error:
            atol = 1e-8
            rtol = 1e-5
        else:
            atol = 0
            rtol = 0

        return bool(
            np.all(
                np.isclose(
                    [self.x, self.y],
                    [other.x, other.y],
                    rtol=rtol,
                    atol=atol,
                    equal_nan=True,
                )
            )
            and (self.visible == other.visible)
            and (self.complete == other.complete)
        )

```

2022-10-03 22:58 UTC, roomrys commented on tests/model/test_instance.py
> +    assert pt1 == pt2
```suggestion
    # test floating point error (error allowed)
    pt1 = Point(x=135.82268970698718, y=213.22842752594835)
    pt2 = Point(x=135.82268970698718, y=213.2284275259484)
    assert pt1 == [pt2, True]

    # test floating point error (no error allowed)
    pt1 = Point(x=135.82268970698718, y=213.22842752594835)
    pt2 = Point(x=135.82268970698718, y=213.2284275259484)
    assert not (pt1 == pt2)
```

2022-10-03 22:58 UTC, roomrys commented on sleap_io/model/instance.py
> +from attrs import define, validators, field, cmp_using
```suggestion
from attrs import define, validators, field
```

2022-10-04 16:25 UTC, quantumdot commented
Hi @roomrys! Thanks for taking a look at this PR. 

I think your proposed changes are reasonable, though it makes comparison a bit kludgy. Only real concern is the "injectability" of this method of comparison. If a comparison happens "deep" in code, but we want to compare on a lower level of precision, there may be no way to inform the system.

Also, will your proposed implementation of `__eq__` on `Point` inherit properly to `PredictedPoint`, under the `attrs` framework? I am not sure myself, mostly due to inexperience with the framework.

An alternative is to set some member(s) within the `instance.py` module to the desired precision level, which are then read by the comparison method. This would impact comparisons globally, but this could either be a good thing or a bad thing depending on what you are trying to do.

Please let me know your thoughts.

2022-10-04 22:00 UTC, roomrys requested changes
Hi @quantumdot,

It does make comparison a bit kludgy. I expanded the comparison out to the instance level with the new suggestions. To compare a list of instances, you would need to create a list for each instance in the comparison (listing the instance and then a bool for whether to allow floating point error). Too kludgy?

I had originally implemented a version where we set an attribute on `Point` to determine whether to allow error, but opted to keep that option for allowing error as an external input. We could revisit that idea if you think it'll be cleaner (and not too unpredictable).

Either way, unless I am missing something, it seems we need to create our own `__eq__` function as `attrs` `cmp_using` is set on a single attribute and doesn't take in external variables (not even self).

2022-10-10 23:21 UTC, quantumdot commented
Hi @roomrys,

I'm afraid it seems to still not work. Using the extra parameter to `__eq__()` means you need to alter equality semantics all the way up the composition chain from `Instance` to `LabeledFrame` to `Labels`, and for each of their derivatives (which could give contributors and consumers trouble). 

Thinking on it for a bit, I like setting class variable(s) on `Point`. I was also thinking a boolean switch may be simplistic and limit control for the user (I expect floating point errors; or I expect _x_% deviation from ground truth; etc). We could add the class variables `Point.eq_atol` and `Point.eq_rtol` with default values of `1e-08` (allow tiny floating point errors) and `0` (do not allow relative errors), respectively, and utilize them in `Point.__eq__()` and child classes as you have in your suggestions. From there, I think no other classes need to be modified except the hook to `_compare_points()` within `Instance`, but that can continue to use `attrs.cmp_using()`. Then then user may turn on/off and tune the precise level of precision they want by setting the class variables on `Point`.

2022-10-11 18:30 UTC, quantumdot commented
Hi @roomrys,

Not sure that I understand your point about adding kwargs to the loading functions--I don't see any comparisons happening during the loading. Since it is a class variable, one does not need to set this on each instance of `Point`. The user can specify tolerance before or after loading. Maybe I misunderstand.

2022-10-11 19:12 UTC, roomrys commented
Hi @quantumdot,

No, I misunderstood. You are totally correct. No need for the extra keyword argument.

2022-10-11 20:26 UTC, quantumdot commented
Hi @roomrys,

Great! Would you like me to make the changes we discussed on this branch? I get a little lost with all the suggestions.

2022-10-11 21:35 UTC, roomrys commented on sleap_io/model/instance.py
> +    return True
Opting to keep the original function.

2022-10-11 21:36 UTC, roomrys commented on sleap_io/model/instance.py
> +        on_setattr=_convert_points, eq=cmp_using(eq=_compare_points)  # type: ignore
Opting to keep the original.

2022-10-11 21:36 UTC, roomrys commented on sleap_io/model/instance.py
> +@define(auto_attribs=True, slots=True, eq=True)
Keep the original.

2022-10-11 21:37 UTC, roomrys commented on sleap_io/model/instance.py
Keep the original.

2022-10-11 21:47 UTC, roomrys commented
Hi @quantumdot,

If you'd prefer to open a new branch that is fine! My bad, I didn't want to hijack your branch (hence all the suggestions floating about). We can link the new PR here for documentation. Let me know if you want me to implement any part of it.

2022-10-12 17:57 UTC, quantumdot commented
Hi @roomrys,

I merged some of your suggestions and made some more commits to get this to (I think) what we discussed. I also got coverage up to 100%. 

One question I ran into was if we want to consider a `Point` and a `PredictedPoint` equal if all base attributes are the same. I fell on the side that `Point() == PredictedPoint()` will always be `False`, but we could adjust this if it does not match the semantics that you would expect.

2022-10-12 22:09 UTC, roomrys commented
Hi @quantumdot,

Agreed, the comparison `Point() == PredictedPoint()` should always be false.

2022-10-12 23:08 UTC, roomrys approved these changes

2022-10-13 19:02 UTC, merged